### ISSUE TITLE
[META] Merge in updates from D7 Rules 7.x-2.13

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#107]
Lots of changes in the [7.x-2.13  D7 release](https://www.drupal.org/project/rules/releases/7.x-2.13). Would be worth going through these and merging the relevant ones into Backdrop Rules.

**Comment by bugfolder** [comment]
From the release notes: changes since 7.x-2.12:

Core Drupal changes:

- [x] ... |  [3250516](https://www.drupal.org/node/3250516) by TR: [D7] PHP 8.1 compatibility - end() — Fixed by https://github.com/backdrop-contrib/rules/pull/152
- [x] ~~... |  [3250518](https://www.drupal.org/node/3250518) by TR: Namespace dependencies in .info files~~ Backdrop currently doesn't support Namespace dependencies in .info files.
- [x] ... |  [3250515](https://www.drupal.org/node/3250515) by TR: [D7] PHP 8.1 compatibility - function_exists().  Fixed by #160 
- [x] ... |  [3250514](https://www.drupal.org/node/3250514) by TR: [D7] PHP 8.1 compatibility - str_replace(). PR #165 
- [x] ... |  [3250504](https://www.drupal.org/node/3250504) by TR: [D7] PHP 8.1 compatibility - #[\ReturnTypeWillChange]. PR #165 
- [x] ~~... |  [3210622](https://www.drupal.org/node/3210622) by TR: [D7] PHP 8.0 introduced breaking change to call_user_func_array()~~ - Already fixed in Backdrop Rules
- [x] ~~... |  [3210626](https://www.drupal.org/node/3210626) by Liam Morland: Required parameters following optional parameters~~ - Already fixed in Backdrop Rules

New features:

- [x] ... |  [2800921](https://www.drupal.org/node/2800921) by TR: Send email to & RFC 2822. PR #171 
- [x] ~~... |  [1236586](https://www.drupal.org/node/1236586) by TR: link tags to their filter pages~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [1349882](https://www.drupal.org/node/1349882) by pluess, jonathan1055, TR: Action: Create a watchdog entry~~ This feature had already been added to Backdrop Rules.
- [x] ~~... |  [2759199](https://www.drupal.org/node/2759199) by Elaman: RTL Rules Components tab~~. This feature had already been added to Backdrop Rules.

Bug fixes:

- [x] <strike>... |  [3245554](https://www.drupal.org/node/3245554) by selfsimilar, TR: `RulesPluginUI::getTags()` makes bad call to `fetchCol()`</strike> Already fixed in Backdrop Rules.
- [x] ~~... |  [2694553](https://www.drupal.org/node/2694553) by nerdoc: Description wrong: "content is of type" should be "Entity is of bundle"~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2340505](https://www.drupal.org/node/2340505) by TR: UI for "Configure access for using this component with a permission" is broken~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [3005864](https://www.drupal.org/node/3005864) by TR: Fix @todo "Enable AJAX once #756762 is fixed"~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2027717](https://www.drupal.org/node/2027717) by TR: Import form doesn't set Rule status to 'Overridden'~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2179781](https://www.drupal.org/node/2179781) by TR: Hiding default-operator in rule conditions is not always a good idea~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2036971](https://www.drupal.org/node/2036971) by TR, catapipper, j0rd: rules_log for conditions doesn't take into account negate when logging result~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2527664](https://www.drupal.org/node/2527664) by TR: Data Calc with dates displays too many operations~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [2191425](https://www.drupal.org/node/2191425) by fubhy: Exceptions in Features UI if Rule lacks event configuration~~ Already fixed in Backdrop Rules.
- [x] ~~... |  [3028444](https://www.drupal.org/node/3028444) by TR: Notice: Undefined index #title at line 5770 ... drupal_pre_render_link~~ Already fixed in Backdrop Rules.

Testing:

- [x] ... |  Need to add new test to .info so that it can be discovered.
- [x] ... |  Refactor rules_admin.test to move minimal profile tests into a new file.

Code cleanup:

- [x] ... |  Change 'is' to 'are' because the subject is plural.
- [x] ... |  [2990280](https://www.drupal.org/node/2990280) by TR: [D7] Coding standards - documentation and indentation.
- [x] ... |  [2990280-46](https://www.drupal.org/node/2990280) by TR: [D7] Coding standards - More documentation comments, including @param, @return, @var.

**Comment by argiepiano** [comment]
PR #152 addresses the first item in the list.

**Comment by argiepiano** [comment]
Regarding namespaced dependencies (2nd item in list). This feature (namespaced dependencies in the info file) seems not to be added to Backdrop. See https://github.com/backdrop/backdrop-issues/issues/3570

**Comment by argiepiano** [comment]
PR #160 ready for review. Fixes the 3rd item: 
| [3250515](https://www.drupal.org/node/3250515) by TR: [D7] PHP 8.1 compatibility - function_exists()

**Comment by bugfolder** [comment]
@argiepiano, thanks for working on these!

So that this issue 107 doesn't get closed automatically when a PR that addresses just one of the items is merged, could we handle the PRs like this:

* Create a single issue for the item being fixed and link to this issue in its description;
* In the PR, put "Addresses [this issue]" and "Fixes [the newly created issue]" in the PR description. (See, for example, https://github.com/backdrop-contrib/rules/pull/152.) The word "Fixes" is magic, and automatically closes the associated issue; "Addresses" has no special behavior.

Then when I (or you) merge the PR, it will close the newly created issue, and we can go in and manually check the appropriate box in this issue, and add a link to the PR that addressed it.

**Comment by argiepiano** [comment]
I've checked the remaining tasks (testing and code cleanup). All of those were already fixed in Backdrop. Closing this issue then.
