### ISSUE TITLE
[META] Bring Backdrop Rules up to date with D7 commits

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/rules#221]
These are [D7 commits](https://git.drupalcode.org/project/rules/-/commits/7.x-2.x) to Rules since the last explictly mentioned merged commit, which was https://git.drupalcode.org/project/rules/-/commit/3ef9835ed7a607cfcea781ea29cc3e05cad3858a, which was merged in via https://github.com/backdrop-contrib/rules/issues/88. Some of these may be unnecessary or already handled; check them off when they're no longer applicable and add commentary if appropriate. Not including DrupalCI issues. Latest issue here (at the bottom) is from 2023-07-10. Once they're all checked off, we should be up to date with D7 Rules 7.x-2.14.

- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/807fac0a24d5ba04865eeb6252a0a33e7b501e06)[#3250504](https://www.drupal.org/i/3250504)[ by TR: [D7] PHP 8.1 compatibility - #[\ReturnTypeWillChange]](https://git.drupalcode.org/project/rules/-/commit/807fac0a24d5ba04865eeb6252a0a33e7b501e06)
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/fcc064bc7fc7fd315c360d0e5ef136a887f8bda7)[#3250514](https://www.drupal.org/i/3250514)[ by TR: [D7] PHP 8.1 compatibility - str_replace()](https://git.drupalcode.org/project/rules/-/commit/fcc064bc7fc7fd315c360d0e5ef136a887f8bda7)
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/e8ab43a782fce4494d87d88b9edf3fcec314d705)[#3250515](https://www.drupal.org/i/3250515)[ by TR: [D7] PHP 8.1 compatibility - function_exists()](https://git.drupalcode.org/project/rules/-/commit/e8ab43a782fce4494d87d88b9edf3fcec314d705)
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/027866d7c666eec81390dcd3b919c0c02816e94c)[#2800921](https://www.drupal.org/i/2800921)[ by TR: Send email to & RFC 2822](https://git.drupalcode.org/project/rules/-/commit/027866d7c666eec81390dcd3b919c0c02816e94c)
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/3c4e18d26e028facd0d26854fcd2de83bccbec5c)[#3250518](https://www.drupal.org/i/3250518)[ by TR: Namespace dependencies in .info files](https://git.drupalcode.org/project/rules/-/commit/3c4e18d26e028facd0d26854fcd2de83bccbec5c) — not relevant to Backdrop
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/3f2e298d06e00039edcae4f1dbb963ba1c163cfb)[#3250516](https://www.drupal.org/i/3250516)[ by TR: [D7] PHP 8.1 compatibility - end()](https://git.drupalcode.org/project/rules/-/commit/3f2e298d06e00039edcae4f1dbb963ba1c163cfb)
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/200b0ea3fc18752d30acd6db7567055e008990ee)[#3252726](https://www.drupal.org/i/3252726)[ by TR: Ensure test events/conditions/actions have a group assigned](https://git.drupalcode.org/project/rules/-/commit/200b0ea3fc18752d30acd6db7567055e008990ee) See https://github.com/backdrop-contrib/rules/issues/222.
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/1b5a0308f1ff1edfa00e5aeedb876cfe528f973b)[#3256912](https://www.drupal.org/i/3256912)[ by klausi, TR: Wrong invocation of RulesEvaluationException...](https://git.drupalcode.org/project/rules/-/commit/1b5a0308f1ff1edfa00e5aeedb876cfe528f973b) See https://github.com/backdrop-contrib/rules/issues/224.
- [x] [Issue ](https://git.drupalcode.org/project/rules/-/commit/716e86463307a64d660f5dce53dcc0727747d7fe)[#3328050](https://www.drupal.org/i/3328050)[ by poker10: PHP 8.2 - Fix deprecated dynamic properties](https://git.drupalcode.org/project/rules/-/commit/716e86463307a64d660f5dce53dcc0727747d7fe)

**Comment by bugfolder** [comment]
We're now up to date with D 7.x-2.14 (and then some). I'll make a new release to get our minor version numbering in sync.
